//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockExchange.WebClient.StockExchangeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://asmx.crossover.com/", ConfigurationName="StockExchangeServiceReference.StockExchangeServiceSoap")]
    public interface StockExchangeServiceSoap {
        
        // CODEGEN: Generating message contract since message AuthenticateUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/AuthenticateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockExchange.WebClient.StockExchangeServiceReference.AuthenticateUserResponse AuthenticateUser(StockExchange.WebClient.StockExchangeServiceReference.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.AuthenticateUserResponse> AuthenticateUserAsync(StockExchange.WebClient.StockExchangeServiceReference.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since message IsUserValidRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/IsUserValid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockExchange.WebClient.StockExchangeServiceReference.IsUserValidResponse IsUserValid(StockExchange.WebClient.StockExchangeServiceReference.IsUserValidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/IsUserValid", ReplyAction="*")]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.IsUserValidResponse> IsUserValidAsync(StockExchange.WebClient.StockExchangeServiceReference.IsUserValidRequest request);
        
        // CODEGEN: Generating message contract since message LogOffRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/LogOff", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockExchange.WebClient.StockExchangeServiceReference.LogOffResponse LogOff(StockExchange.WebClient.StockExchangeServiceReference.LogOffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/LogOff", ReplyAction="*")]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.LogOffResponse> LogOffAsync(StockExchange.WebClient.StockExchangeServiceReference.LogOffRequest request);
        
        // CODEGEN: Generating message contract since message GetCurrentUserIdRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/GetCurrentUserId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockExchange.WebClient.StockExchangeServiceReference.GetCurrentUserIdResponse GetCurrentUserId(StockExchange.WebClient.StockExchangeServiceReference.GetCurrentUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/GetCurrentUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.GetCurrentUserIdResponse> GetCurrentUserIdAsync(StockExchange.WebClient.StockExchangeServiceReference.GetCurrentUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/CreateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockExchange.WebClient.StockExchangeServiceReference.MembershipCreateStatus CreateUser(StockExchange.WebClient.StockExchangeServiceReference.RegisterUserModel registerUserModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/CreateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.MembershipCreateStatus> CreateUserAsync(StockExchange.WebClient.StockExchangeServiceReference.RegisterUserModel registerUserModel);
        
        // CODEGEN: Generating message contract since message AddStockToUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/AddStockToUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockExchange.WebClient.StockExchangeServiceReference.AddStockToUserResponse AddStockToUser(StockExchange.WebClient.StockExchangeServiceReference.AddStockToUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/AddStockToUser", ReplyAction="*")]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.AddStockToUserResponse> AddStockToUserAsync(StockExchange.WebClient.StockExchangeServiceReference.AddStockToUserRequest request);
        
        // CODEGEN: Generating message contract since message RemoveStockFromUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/RemoveStockFromUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockExchange.WebClient.StockExchangeServiceReference.RemoveStockFromUserResponse RemoveStockFromUser(StockExchange.WebClient.StockExchangeServiceReference.RemoveStockFromUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/RemoveStockFromUser", ReplyAction="*")]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.RemoveStockFromUserResponse> RemoveStockFromUserAsync(StockExchange.WebClient.StockExchangeServiceReference.RemoveStockFromUserRequest request);
        
        // CODEGEN: Generating message contract since message GetStocksRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/GetStocks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockExchange.WebClient.StockExchangeServiceReference.GetStocksResponse GetStocks(StockExchange.WebClient.StockExchangeServiceReference.GetStocksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/GetStocks", ReplyAction="*")]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.GetStocksResponse> GetStocksAsync(StockExchange.WebClient.StockExchangeServiceReference.GetStocksRequest request);
        
        // CODEGEN: Generating message contract since message GetUserStocksRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/GetUserStocks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockExchange.WebClient.StockExchangeServiceReference.GetUserStocksResponse GetUserStocks(StockExchange.WebClient.StockExchangeServiceReference.GetUserStocksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asmx.crossover.com/GetUserStocks", ReplyAction="*")]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.GetUserStocksResponse> GetUserStocksAsync(StockExchange.WebClient.StockExchangeServiceReference.GetUserStocksRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmx.crossover.com/")]
    public partial class SecuredWebServiceHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid userIdField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string authenticatedTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AuthenticatedToken {
            get {
                return this.authenticatedTokenField;
            }
            set {
                this.authenticatedTokenField = value;
                this.RaisePropertyChanged("AuthenticatedToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmx.crossover.com/")]
    public partial class RegisterUserModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string userPasswordField;
        
        private string userEmailField;
        
        private string userQuestionField;
        
        private string userAnswerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserPassword {
            get {
                return this.userPasswordField;
            }
            set {
                this.userPasswordField = value;
                this.RaisePropertyChanged("UserPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserEmail {
            get {
                return this.userEmailField;
            }
            set {
                this.userEmailField = value;
                this.RaisePropertyChanged("UserEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserQuestion {
            get {
                return this.userQuestionField;
            }
            set {
                this.userQuestionField = value;
                this.RaisePropertyChanged("UserQuestion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UserAnswer {
            get {
                return this.userAnswerField;
            }
            set {
                this.userAnswerField = value;
                this.RaisePropertyChanged("UserAnswer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUser", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://asmx.crossover.com/")]
        public StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUserResponse", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmx.crossover.com/", Order=0)]
        public string AuthenticateUserResult;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(string AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUserValid", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class IsUserValidRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://asmx.crossover.com/")]
        public StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        public IsUserValidRequest() {
        }
        
        public IsUserValidRequest(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUserValidResponse", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class IsUserValidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmx.crossover.com/", Order=0)]
        public bool IsUserValidResult;
        
        public IsUserValidResponse() {
        }
        
        public IsUserValidResponse(bool IsUserValidResult) {
            this.IsUserValidResult = IsUserValidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogOff", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class LogOffRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://asmx.crossover.com/")]
        public StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        public LogOffRequest() {
        }
        
        public LogOffRequest(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogOffResponse", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class LogOffResponse {
        
        public LogOffResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrentUserId", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class GetCurrentUserIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://asmx.crossover.com/")]
        public StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        public GetCurrentUserIdRequest() {
        }
        
        public GetCurrentUserIdRequest(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrentUserIdResponse", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class GetCurrentUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmx.crossover.com/", Order=0)]
        public System.Guid GetCurrentUserIdResult;
        
        public GetCurrentUserIdResponse() {
        }
        
        public GetCurrentUserIdResponse(System.Guid GetCurrentUserIdResult) {
            this.GetCurrentUserIdResult = GetCurrentUserIdResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmx.crossover.com/")]
    public enum MembershipCreateStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        InvalidUserName,
        
        /// <remarks/>
        InvalidPassword,
        
        /// <remarks/>
        InvalidQuestion,
        
        /// <remarks/>
        InvalidAnswer,
        
        /// <remarks/>
        InvalidEmail,
        
        /// <remarks/>
        DuplicateUserName,
        
        /// <remarks/>
        DuplicateEmail,
        
        /// <remarks/>
        UserRejected,
        
        /// <remarks/>
        InvalidProviderUserKey,
        
        /// <remarks/>
        DuplicateProviderUserKey,
        
        /// <remarks/>
        ProviderError,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddStockToUser", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class AddStockToUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://asmx.crossover.com/")]
        public StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmx.crossover.com/", Order=0)]
        public System.Guid userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmx.crossover.com/", Order=1)]
        public string stockCode;
        
        public AddStockToUserRequest() {
        }
        
        public AddStockToUserRequest(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, System.Guid userId, string stockCode) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.userId = userId;
            this.stockCode = stockCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddStockToUserResponse", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class AddStockToUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmx.crossover.com/", Order=0)]
        public string AddStockToUserResult;
        
        public AddStockToUserResponse() {
        }
        
        public AddStockToUserResponse(string AddStockToUserResult) {
            this.AddStockToUserResult = AddStockToUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveStockFromUser", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class RemoveStockFromUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://asmx.crossover.com/")]
        public StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmx.crossover.com/", Order=0)]
        public System.Guid userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmx.crossover.com/", Order=1)]
        public string stockCode;
        
        public RemoveStockFromUserRequest() {
        }
        
        public RemoveStockFromUserRequest(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, System.Guid userId, string stockCode) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.userId = userId;
            this.stockCode = stockCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveStockFromUserResponse", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class RemoveStockFromUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmx.crossover.com/", Order=0)]
        public string RemoveStockFromUserResult;
        
        public RemoveStockFromUserResponse() {
        }
        
        public RemoveStockFromUserResponse(string RemoveStockFromUserResult) {
            this.RemoveStockFromUserResult = RemoveStockFromUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStocks", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class GetStocksRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://asmx.crossover.com/")]
        public StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmx.crossover.com/", Order=0)]
        public string prefixFilter;
        
        public GetStocksRequest() {
        }
        
        public GetStocksRequest(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, string prefixFilter) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.prefixFilter = prefixFilter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStocksResponse", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class GetStocksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmx.crossover.com/", Order=0)]
        public string GetStocksResult;
        
        public GetStocksResponse() {
        }
        
        public GetStocksResponse(string GetStocksResult) {
            this.GetStocksResult = GetStocksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserStocks", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class GetUserStocksRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://asmx.crossover.com/")]
        public StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmx.crossover.com/", Order=0)]
        public System.Guid userId;
        
        public GetUserStocksRequest() {
        }
        
        public GetUserStocksRequest(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, System.Guid userId) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserStocksResponse", WrapperNamespace="http://asmx.crossover.com/", IsWrapped=true)]
    public partial class GetUserStocksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asmx.crossover.com/", Order=0)]
        public string GetUserStocksResult;
        
        public GetUserStocksResponse() {
        }
        
        public GetUserStocksResponse(string GetUserStocksResult) {
            this.GetUserStocksResult = GetUserStocksResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockExchangeServiceSoapChannel : StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockExchangeServiceSoapClient : System.ServiceModel.ClientBase<StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap>, StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap {
        
        public StockExchangeServiceSoapClient() {
        }
        
        public StockExchangeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockExchangeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockExchangeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockExchangeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockExchange.WebClient.StockExchangeServiceReference.AuthenticateUserResponse StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.AuthenticateUser(StockExchange.WebClient.StockExchangeServiceReference.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public string AuthenticateUser(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            StockExchange.WebClient.StockExchangeServiceReference.AuthenticateUserRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.AuthenticateUserRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            StockExchange.WebClient.StockExchangeServiceReference.AuthenticateUserResponse retVal = ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).AuthenticateUser(inValue);
            return retVal.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.AuthenticateUserResponse> StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.AuthenticateUserAsync(StockExchange.WebClient.StockExchangeServiceReference.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.AuthenticateUserResponse> AuthenticateUserAsync(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            StockExchange.WebClient.StockExchangeServiceReference.AuthenticateUserRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.AuthenticateUserRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            return ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockExchange.WebClient.StockExchangeServiceReference.IsUserValidResponse StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.IsUserValid(StockExchange.WebClient.StockExchangeServiceReference.IsUserValidRequest request) {
            return base.Channel.IsUserValid(request);
        }
        
        public bool IsUserValid(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            StockExchange.WebClient.StockExchangeServiceReference.IsUserValidRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.IsUserValidRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            StockExchange.WebClient.StockExchangeServiceReference.IsUserValidResponse retVal = ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).IsUserValid(inValue);
            return retVal.IsUserValidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.IsUserValidResponse> StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.IsUserValidAsync(StockExchange.WebClient.StockExchangeServiceReference.IsUserValidRequest request) {
            return base.Channel.IsUserValidAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.IsUserValidResponse> IsUserValidAsync(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            StockExchange.WebClient.StockExchangeServiceReference.IsUserValidRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.IsUserValidRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            return ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).IsUserValidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockExchange.WebClient.StockExchangeServiceReference.LogOffResponse StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.LogOff(StockExchange.WebClient.StockExchangeServiceReference.LogOffRequest request) {
            return base.Channel.LogOff(request);
        }
        
        public void LogOff(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            StockExchange.WebClient.StockExchangeServiceReference.LogOffRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.LogOffRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            StockExchange.WebClient.StockExchangeServiceReference.LogOffResponse retVal = ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).LogOff(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.LogOffResponse> StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.LogOffAsync(StockExchange.WebClient.StockExchangeServiceReference.LogOffRequest request) {
            return base.Channel.LogOffAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.LogOffResponse> LogOffAsync(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            StockExchange.WebClient.StockExchangeServiceReference.LogOffRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.LogOffRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            return ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).LogOffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockExchange.WebClient.StockExchangeServiceReference.GetCurrentUserIdResponse StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.GetCurrentUserId(StockExchange.WebClient.StockExchangeServiceReference.GetCurrentUserIdRequest request) {
            return base.Channel.GetCurrentUserId(request);
        }
        
        public System.Guid GetCurrentUserId(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            StockExchange.WebClient.StockExchangeServiceReference.GetCurrentUserIdRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.GetCurrentUserIdRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            StockExchange.WebClient.StockExchangeServiceReference.GetCurrentUserIdResponse retVal = ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).GetCurrentUserId(inValue);
            return retVal.GetCurrentUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.GetCurrentUserIdResponse> StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.GetCurrentUserIdAsync(StockExchange.WebClient.StockExchangeServiceReference.GetCurrentUserIdRequest request) {
            return base.Channel.GetCurrentUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.GetCurrentUserIdResponse> GetCurrentUserIdAsync(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            StockExchange.WebClient.StockExchangeServiceReference.GetCurrentUserIdRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.GetCurrentUserIdRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            return ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).GetCurrentUserIdAsync(inValue);
        }
        
        public StockExchange.WebClient.StockExchangeServiceReference.MembershipCreateStatus CreateUser(StockExchange.WebClient.StockExchangeServiceReference.RegisterUserModel registerUserModel) {
            return base.Channel.CreateUser(registerUserModel);
        }
        
        public System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.MembershipCreateStatus> CreateUserAsync(StockExchange.WebClient.StockExchangeServiceReference.RegisterUserModel registerUserModel) {
            return base.Channel.CreateUserAsync(registerUserModel);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockExchange.WebClient.StockExchangeServiceReference.AddStockToUserResponse StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.AddStockToUser(StockExchange.WebClient.StockExchangeServiceReference.AddStockToUserRequest request) {
            return base.Channel.AddStockToUser(request);
        }
        
        public string AddStockToUser(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, System.Guid userId, string stockCode) {
            StockExchange.WebClient.StockExchangeServiceReference.AddStockToUserRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.AddStockToUserRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.userId = userId;
            inValue.stockCode = stockCode;
            StockExchange.WebClient.StockExchangeServiceReference.AddStockToUserResponse retVal = ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).AddStockToUser(inValue);
            return retVal.AddStockToUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.AddStockToUserResponse> StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.AddStockToUserAsync(StockExchange.WebClient.StockExchangeServiceReference.AddStockToUserRequest request) {
            return base.Channel.AddStockToUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.AddStockToUserResponse> AddStockToUserAsync(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, System.Guid userId, string stockCode) {
            StockExchange.WebClient.StockExchangeServiceReference.AddStockToUserRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.AddStockToUserRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.userId = userId;
            inValue.stockCode = stockCode;
            return ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).AddStockToUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockExchange.WebClient.StockExchangeServiceReference.RemoveStockFromUserResponse StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.RemoveStockFromUser(StockExchange.WebClient.StockExchangeServiceReference.RemoveStockFromUserRequest request) {
            return base.Channel.RemoveStockFromUser(request);
        }
        
        public string RemoveStockFromUser(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, System.Guid userId, string stockCode) {
            StockExchange.WebClient.StockExchangeServiceReference.RemoveStockFromUserRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.RemoveStockFromUserRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.userId = userId;
            inValue.stockCode = stockCode;
            StockExchange.WebClient.StockExchangeServiceReference.RemoveStockFromUserResponse retVal = ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).RemoveStockFromUser(inValue);
            return retVal.RemoveStockFromUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.RemoveStockFromUserResponse> StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.RemoveStockFromUserAsync(StockExchange.WebClient.StockExchangeServiceReference.RemoveStockFromUserRequest request) {
            return base.Channel.RemoveStockFromUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.RemoveStockFromUserResponse> RemoveStockFromUserAsync(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, System.Guid userId, string stockCode) {
            StockExchange.WebClient.StockExchangeServiceReference.RemoveStockFromUserRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.RemoveStockFromUserRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.userId = userId;
            inValue.stockCode = stockCode;
            return ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).RemoveStockFromUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockExchange.WebClient.StockExchangeServiceReference.GetStocksResponse StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.GetStocks(StockExchange.WebClient.StockExchangeServiceReference.GetStocksRequest request) {
            return base.Channel.GetStocks(request);
        }
        
        public string GetStocks(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, string prefixFilter) {
            StockExchange.WebClient.StockExchangeServiceReference.GetStocksRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.GetStocksRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.prefixFilter = prefixFilter;
            StockExchange.WebClient.StockExchangeServiceReference.GetStocksResponse retVal = ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).GetStocks(inValue);
            return retVal.GetStocksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.GetStocksResponse> StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.GetStocksAsync(StockExchange.WebClient.StockExchangeServiceReference.GetStocksRequest request) {
            return base.Channel.GetStocksAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.GetStocksResponse> GetStocksAsync(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, string prefixFilter) {
            StockExchange.WebClient.StockExchangeServiceReference.GetStocksRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.GetStocksRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.prefixFilter = prefixFilter;
            return ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).GetStocksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockExchange.WebClient.StockExchangeServiceReference.GetUserStocksResponse StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.GetUserStocks(StockExchange.WebClient.StockExchangeServiceReference.GetUserStocksRequest request) {
            return base.Channel.GetUserStocks(request);
        }
        
        public string GetUserStocks(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, System.Guid userId) {
            StockExchange.WebClient.StockExchangeServiceReference.GetUserStocksRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.GetUserStocksRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.userId = userId;
            StockExchange.WebClient.StockExchangeServiceReference.GetUserStocksResponse retVal = ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).GetUserStocks(inValue);
            return retVal.GetUserStocksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.GetUserStocksResponse> StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap.GetUserStocksAsync(StockExchange.WebClient.StockExchangeServiceReference.GetUserStocksRequest request) {
            return base.Channel.GetUserStocksAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockExchange.WebClient.StockExchangeServiceReference.GetUserStocksResponse> GetUserStocksAsync(StockExchange.WebClient.StockExchangeServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, System.Guid userId) {
            StockExchange.WebClient.StockExchangeServiceReference.GetUserStocksRequest inValue = new StockExchange.WebClient.StockExchangeServiceReference.GetUserStocksRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.userId = userId;
            return ((StockExchange.WebClient.StockExchangeServiceReference.StockExchangeServiceSoap)(this)).GetUserStocksAsync(inValue);
        }
    }
}
